# Header

menu:
  我的主页: /
  随笔一篇: /categories/随笔一篇/
  前端技术: /categories/前端技术/
  后端技术: /categories/后端技术/
  其他技术: /categories/其他技术/

# SubNav
subnav:
  github: "http://github.com/homfen"
  weibo: "http://weibo.com/homfen"
  #rss: "#"
  #zhihu: "#"
  #douban: "#"
  #facebook: "http://www.facebook.com/homfen"
  #google: "#"
  twitter: "http://twitter.com/homfen"
  #linkedin: "#"
  mail: "mailto:homfen[@]gmail.com"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content
excerpt_link: more
fancybox: false 
mathjax: false

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ""
favicon: images/favicon.ico

#你的头像url
avatar: /images/avatar.png

#是否开启分享
share_jia: false 
share_addthis: false

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: "homfenblog"

# 如不需要，将该项置为false
# 比如
#smart_menu:
#  friends: false

smart_menu:
  innerArchive: '所有文章'
  categorycloud: '分类'
  tagcloud: '标签'
  friends: '友链'
  #aboutme: '关于我'

friends:
  huajh7: http://www.huajh7.com/

aboutme: 很惭愧<br><br>只做了一点微小的工作<br>谢谢大家
